---

- name: Nginx Install | Modules | Download the geoip lib source
  get_url:
    url: "{{nginx_geoip_url}}"
    dest: "/tmp/geolib-{{nginx_geoip_version}}.tar.gz"

- name: Nginx Install | Modules | Unpack the geoip library source
  command: "tar -xvzf /tmp/geolib-{{nginx_geoip_version}}.tar.gz"
  args:
    chdir:   "/tmp"
    creates: "/tmp/GeoIP-{{nginx_geoip_version}}"

- name: Nginx Install | Modules | Install the geoip library
  shell: >
    cd "/tmp/GeoIP-{{nginx_geoip_version}}" &&
    ./configure && 
    make &&
    make install


