---
- include: 'prepare.yml'

- include: 'install.yml'
  when: old_checksum.stdout != new_checksum.stdout

- name: Nginx Configure | Set current checksum
  command: "mv '{{nginx_dir}}/.nginx_compile_configuration.new' '{{nginx_dir}}/.nginx_compile_configuration'"

- name: Nginx Configure | Set current user checksum
  command: "mv '{{nginx_dir}}/.nginx_user_configuration.new' '{{nginx_dir}}/.nginx_user_configuration'"

- include: 'configure.yml'
