# file: nginx/tasks/modules/http_stub_status_module.yml
# configure flag: --with-http_stub_status_module

- include: _authorized_ips.yml

- name: Nginx Configure | Modules | Make sure the nginx status configuration is updated when enabled
  template:
    src: ../../templates/modules/nginx_status.j2
    dest: "{{nginx_dir}}/sites-available/nginx_status"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  when: nginx_modules.http_stub_status_module is defined and ( nginx_modules.http_stub_status_module == true or nginx_modules.http_stub_status_module == 'True' )

- name: Nginx Configure | Modules | Make sure the nginx status configuration is removed when disabled
  file:
    path: "{{nginx_dir}}/sites-available/nginx_status"
    state: absent
  notify:
    - reload nginx
  when: nginx_modules.http_stub_status_module is not defined or nginx_modules.http_stub_status_module == false or nginx_modules.http_stub_status_module == 'False' 


