---
- name: Nginx Configure | Modules | Make sure the naxsi_module configuration is up to date when enabled
  copy:
    src: ../../files/naxsi_core.rules
    dest: "{{nginx_dir}}/naxsi_core.rules"
    owner: root
    group: root
    mode: 0644
  when: nginx_modules.naxsi_module is defined and nginx_modules.naxsi_module == true

- name: Nginx Configure | Modules | Make sure the naxsi_module configuration is removed when disabled 
  file:
    path: "{{nginx_dir}}/naxsi_core.rules"
    state: absent
  when: nginx_modules.naxsi_module is not defined or nginx_modules.naxsi_module == false

